export const API = {
  auth: {
    login:   '/auth/login',
    refresh: '/auth/refresh',
    logout:  '/auth/logout',
  },
  dashboard: '/dashboard',
  documents: {
    list:    '/documents',
    detail:  (id: number) => `/documents/${id}`,
    versions:(id: number) => `/documents/${id}/versions`,
    upload:  (id: number) => `/documents/${id}/versions/upload`,
    publish: (id: number, v: number) => `/documents/${id}/versions/${v}/publish`,
    retire:  (id: number, v: number) => `/documents/${id}/versions/${v}/retire`,
  },
  worksheets: {
    list:    '/worksheets',
    start:   (docId: number) => `/worksheets/start/${docId}`,
    detail:  (id: number) => `/worksheets/${id}`,
    submit:  (id: number) => `/worksheets/${id}/submit`,
    approve: (id: number) => `/worksheets/${id}/approve`,
    reject:  (id: number) => `/worksheets/${id}/reject`,
  },
  oos: {
    list:       '/api/oos',
    detail:     (id: number) => `/api/oos/${id}`,
    investigate:(id: number) => `/api/oos/${id}/investigate`,
    approve:    (id: number) => `/api/oos/${id}/approve`,
  },
  chemicals: {
    masters:  '/chemicals/masters',
    master:   (id: number) => `/chemicals/masters/${id}`,
    register: '/chemicals/register',
    stock:    '/chemicals/stock',
    issue:    '/chemicals/issue',
    destroy:  '/chemicals/destroy',
    containers: '/chemicals/containers',
    container:  (id: number) => `/chemicals/containers/${id}`,
    fefo:     '/chemicals/fefo',
  },
  storage: {
    list:    '/api/storage',
    detail:  (id: number) => `/api/storage/${id}`,
    place:   '/api/storage/place',
    move:    '/api/storage/move',
    violations: '/api/storage/violations',
  },
  instruments: {
    list:         '/instruments',
    detail:       (id: number) => `/instruments/${id}`,
    calibrations: (id: number) => `/instruments/${id}/calibrations`,
    reservations: '/instruments/reservations',
    reservation:  (id: number) => `/instruments/reservations/${id}`,
    downtime:     (id: number) => `/instruments/${id}/downtime`,
    limits:       (id: number) => `/instruments/${id}/limits`,
  },
  barcode: {
    scan:       '/api/barcode/scan',
    scanUniversal: '/api/barcode/universal',
  },
  eln: {
    list:   '/api/eln',
    detail: (id: number) => `/api/eln/${id}`,
  },
  training: {
    materials: '/api/training/materials',
    assign:    '/api/training/assign',
    records:   '/api/training/records',
  },
  tasks: {
    list:   '/tasks',
    detail: (id: number) => `/tasks/${id}`,
    accept: (id: number) => `/tasks/${id}/accept`,
    complete: (id: number) => `/tasks/${id}/complete`,
  },
  notifications: {
    list:    '/api/notifications',
    markRead:(id: number) => `/api/notifications/${id}/read`,
    emailLog:'/api/notifications/email-log',
  },
  audit: {
    list:   '/audit',
    entity: (type: string, id: number) => `/audit/entity/${type}/${id}`,
  },
  analytics: {
    chemical:    '/api/analytics/chemical',
    instrument:  '/api/analytics/instrument',
    worksheet:   '/api/analytics/worksheet',
    user:        '/api/analytics/user',
    storage:     '/api/analytics/storage',
    predictive:  '/api/analytics/predictive',
    oos:         '/api/analytics/oos',
  },
  users: {
    list:   '/users',
    detail: (id: number) => `/users/${id}`,
    create: '/users',
    roles:  (id: number) => `/users/${id}/roles`,
    skills: (id: number) => `/users/${id}/skills`,
  },
  tenants: {
    list:     '/tenants',
    detail:   (id: number) => `/tenants/${id}`,
    branches: (id: number) => `/tenants/${id}/branches`,
  },
  suppliers: {
    list:   '/suppliers',
    detail: (id: number) => `/suppliers/${id}`,
    rate:   (id: number) => `/suppliers/${id}/rating`,
    docs:   (id: number) => `/suppliers/${id}/documents`,
  },
  qa: {
    deviations: '/qa/deviations',
    deviation:  (id: number) => `/qa/deviations/${id}`,
    capas:      '/qa/capas',
    capa:       (id: number) => `/qa/capas/${id}`,
    ooscases:   '/qa/oos-cases',
  },
  samples: {
    list:    '/samples',
    detail:  (id: number) => `/samples/${id}`,
    tests:   (id: number) => `/samples/${id}/tests`,
    results: (id: number) => `/samples/${id}/results`,
    coa:     (id: number) => `/samples/${id}/coa`,
  },
} as const;
